dist:
  name: otel-collector-custom
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev

exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/debugexporter v0.136.0
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.136.0

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.136.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.136.0

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver v0.136.0
#  - gomod: github.com/Grandys/opentelemetry-collector-contrib/receiver/postgresqlreceiver 1742207758d6411c4678cc64dc80288966183a67

# To test changes from fork, replace otel component with fork github path, for example:
#  - gomod: github.com/Grandys/opentelemetry-collector-contrib/receiver/postgresqlreceiver reciver-backends-app-names
# Where 1742207758d6411c4678cc64dc80288966183a67 is a revision (commit/tag/branch ...)
# Next, rename component module name in the fork, to match fork repository path. Here is an example:
# https://github.com/Grandys/opentelemetry-collector-contrib/commit/71eb60da4e37496c9d18e369d2ddca040f6c7491
#

replaces:
  - github.com/open-telemetry/opentelemetry-collector-contrib/internal/sqlquery => github.com/open-telemetry/opentelemetry-collector-contrib/internal/sqlquery v0.136.0