services:

  # Collector
  otel-collector:
    image: "otel/opentelemetry-collector-contrib:0.109.0"
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    profiles:
      - otel-contrib
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension

  lgtm:
    image: grafana/otel-lgtm
    container_name: lgtm
    ports:
      - "3000:3000"
      - "4317:4317"
  postgres:
    image: postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5432:5432"
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./pg_data/init.sql:/docker-entrypoint-initdb.d/init.sql
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: otel
      POSTGRES_USER: otel
      POSTGRES_DB: otel 

