receivers:
  sqlquery:
    driver: postgres
    host: localhost
    port: 5432
    username: otel
    password: otel
    database: otel
    additional_params:
      sslmode: disable
    queries:
      - sql: "select log_type, max(datapoint) as datapoint from logs_data group by log_type"
        metrics:
          - metric_name: logs.datapoint
            value_column: "datapoint"
            attribute_columns: [ "log_type" ]
      - sql: "select 'Max datapoint value for ' || log_type || ' is ' || max(datapoint) as datapoint, log_type from logs_data group by log_type"
        logs:
          - body_column: datapoint
            attribute_columns: [ "log_type" ]
  postgresql:
    endpoint: localhost:5432
    transport: tcp
    username: otel
    password: otel
    databases:
      - otel
    collection_interval: 10s
    tls:
      insecure: true
    metrics: # Enable metrics disabled by default: to https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/postgresqlreceiver/metadata.yaml
      postgresql.sequential_scans:
        enabled: true


exporters:
  debug:
  otlp/lgtm:
    endpoint: localhost:4317
    tls:
      insecure: true


processors:
  batch:
  resource/sqlquery:
    attributes:
      - key: service.name
        value: "sql-query-reader"
        action: insert
  resource/postgresql:
    attributes:
      - key: service.name
        value: "postgresql"
        action: insert

service:
  pipelines:
    metrics/sqlquery:
      receivers: [ sqlquery ]
      processors: [ resource/sqlquery, batch ]
      exporters: [ debug,otlp/lgtm ]
    logs/sqlquery:
      receivers: [ sqlquery ]
      processors: [ resource/sqlquery, batch ]
      exporters: [ debug,otlp/lgtm ]
    metrics/postgresql:
      receivers: [ postgresql ]
      processors: [ resource/postgresql, batch ]
      exporters: [ debug,otlp/lgtm ]
